// <auto-generated />
using System;
using CarsFipe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarsFipe.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarsFipe.Models.Car", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int>("AnoModelo")
                        .HasColumnType("INT")
                        .HasColumnName("AnoModelo");

                    b.Property<string>("CodigoFipe")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("CodigoFipe");

                    b.Property<string>("Combustivel")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Combustivel");

                    b.Property<string>("DataConsulta")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("DataConsulta");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Marca");

                    b.Property<string>("MesReferencia")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("MesReferencia");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Placa");

                    b.Property<string>("SiglaCombustivel")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("SiglaCombustivel");

                    b.Property<int>("TipoVeiculo")
                        .HasColumnType("INT")
                        .HasColumnName("TipoVeiculo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "IX_Car")
                        .IsUnique();

                    b.ToTable("Cars", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
